In [ ]:
import numpy as np

In [ ]:
# Example 1
v1 = np.array([1,1,1])
v2 = np.array([1,-1,2])
v3 = np.array([-1,1,3])

v = np.array([v1,v2,v3])

In [7]:
# Example 2
v1 = np.array([1,1,0])
v2 = np.array([1,3,1])
v3 = np.array([2,-1,1])

v = np.array([v1,v2,v3])

In [12]:
# explicit function to normalize array
def normalize_2d(v):
    norm = np.linalg.norm(v)
    v = v/norm  # normalized matrix
    return v

In [17]:
def orthogonal(v):
    vpp = np.empty((0, v.shape[1]))
    for i in v:
        vp = i
        for j in vpp:
            vp = vp - np.inner(i, j) * j
        vp = normalize_2d(vp)
        vpp = np.vstack([vpp, vp])
    return vpp

print(orthogonal(v))


[[ 0.70710678  0.70710678  0.        ]
 [-0.57735027  0.57735027  0.57735027]
 [ 0.40824829 -0.40824829  0.81649658]]


In [16]:
print (1 / np.sqrt(2) * np.array([1,1,0]))
print (1 / np.sqrt(3) * np.array([-1,1,1]))
print (1 / np.sqrt(6) * np.array([1,-1,2]))


[0.70710678 0.70710678 0.        ]
[-0.57735027  0.57735027  0.57735027]
[ 0.40824829 -0.40824829  0.81649658]
